package kg.study.covid.util

import android.content.Context
import androidx.swiperefreshlayout.widget.CircularProgressDrawable

fun getProgressDrawable(context: Context) : CircularProgressDrawable {
    return CircularProgressDrawable(context).apply {
        strokeWidth = 10f
        centerRadius = 50f
        start()
    }
}

fun transliteration(country: String, divider: String = " "): String {
    return country.replace(" ", divider)
        .replace("China", "Китай")
        .replace("Italy", "Италия")
        .replace("Spain", "V")
        .replace("Usa", "G")
        .replace("Germany", "D")
        .replace("Iran", "E")
        .replace("France", "E")
        .replace("S.Korea", "ZH")
        .replace("Switzerland", "Z")
        .replace("UK", "I")
        .replace("Netherlands", "I")
        .replace("Belgium", "K")
        .replace("Austria", "L")
        .replace("Norway", "M")
        .replace("Sweden", "N")
        .replace("Portugal", "O")
        .replace("Denmark", "P")
        .replace("Australia", "R")
        .replace("Canada", "S")
        .replace("Malaysia", "T")
        .replace("Brazil", "U")
        .replace("Japan", "F")
        .replace("Czechia", "H")
        .replace("Turkey", "C")
        .replace("Israel", "CH")
        .replace("Luxembourg", "SH")
        .replace("Ireland", "SH")
        .replace("Pakistan", "")
        .replace("Diamond Princess", "I")
        .replace("Finland", "")
        .replace("Thailand", "E")
        .replace("Iceland", "YU")
        .replace("Poland", "YA")
        .replace("Chile", "a")
        .replace("Ecuator", "b")
        .replace("Greece", "v")
        .replace("Indonesia", "g")
        .replace("Saudi Arabia", "d")
        .replace("Qatar", "e")
        .replace("Singapore", "e")
        .replace("Romania", "zh")
        .replace("Slovenia", "z")
        .replace("Philippines", "i")
        .replace("Russia", "i")
        .replace("India", "k")
        .replace("Bahrain", "l")
        .replace("Estonia", "m")
        .replace("Peru", "n")
        .replace("Egypt", "o")
        .replace("Hong Kong", "p")
        .replace("Mexico", "r")
        .replace("lebanon", "s")
        .replace("Panama", "t")
        .replace("South Africa", "u")
        .replace("Croatia", "f")
        .replace("Iraq", "h")
        .replace("Argentina", "c")
        .replace("Colombia", "ch")
        .replace("Armenia", "sh")
        .replace("Serbia", "sh")
        .replace("Kuwait", "")
        .replace("Slovakia", "i")
        .replace("San Marino", "")
        .replace("Bulgaria", "e")
        .replace("Taiwan", "yu")
        .replace("UAE", "yu")
        .replace("Algeria", "yu")
        .replace("Latvia", "yu")
        .replace("Uruguay", "yu")
        .replace("Hungary", "yu")
        .replace("Costa Rica", "yu")
        .replace("North Macedonia", "yu")
        .replace("ю", "yu")
        .replace("ю", "yu")
        .replace("ю", "yu")
        .replace("ю", "yu")
        .replace("ю", "yu")
        .replace("ю", "yu")
        .replace("ю", "yu")
        .replace("ю", "yu")
        .replace("ю", "yu")
        .replace("я", "ya")


}
